name: Go

on:
  push:
    branches:
      - master    
    tags:
      - '*'    
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.3

    - name: Build
      run: go build -trimpath -ldflags="-w -s -X 'main.Version=$VERSION'" -v ./...

    - name: Test
      run: go test -cover -v ./...