name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_VERSION: 1.0.0-alpha
    steps:
    - uses: actions/checkout@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.3

    - name: Build
      run: go build -trimpath -ldflags="-w -s -X 'main.Version=$PROJECT_VERSION'" -v ./...

    - name: Test
      run: go test -cover -v ./...